package hibernate;
// Generated 2016-9-8 14:30:58 by Hibernate Tools 3.5.0.Final

/**
 * Administrator generated by hbm2java
 */
public class Administrator implements java.io.Serializable {

	private int aid;
	private String apwd;

	public Administrator() {
	}

	public Administrator(int aid, String apwd) {
		this.aid = aid;
		this.apwd = apwd;
	}

	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	public String getApwd() {
		return this.apwd;
	}

	public void setApwd(String apwd) {
		this.apwd = apwd;
	}

}
