package hibernate;
// Generated 2016-9-13 19:11:22 by Hibernate Tools 3.5.0.Final

/**
 * ECs generated by hbm2java
 */
public class ECs implements java.io.Serializable {

	private Integer csid;
	private Integer classs;
	private Integer grade;
	private String csadd;

	public ECs() {
	}

	public ECs(Integer classs, Integer grade, String csadd) {
		this.classs = classs;
		this.grade = grade;
		this.csadd = csadd;
	}

	public Integer getCsid() {
		return this.csid;
	}

	public void setCsid(Integer csid) {
		this.csid = csid;
	}

	public Integer getClasss() {
		return this.classs;
	}

	public void setClasss(Integer classs) {
		this.classs = classs;
	}

	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	public String getCsadd() {
		return this.csadd;
	}

	public void setCsadd(String csadd) {
		this.csadd = csadd;
	}

}
