package hibernate;
// Generated 2016-9-8 14:30:58 by Hibernate Tools 3.5.0.Final

/**
 * ECs generated by hbm2java
 */
public class ECs implements java.io.Serializable {

	private Integer csid;
	private Integer class_;
	private Integer grade;
	private String csadd;

	public ECs() {
	}

	public ECs(Integer class_, Integer grade, String csadd) {
		this.class_ = class_;
		this.grade = grade;
		this.csadd = csadd;
	}

	public Integer getCsid() {
		return this.csid;
	}

	public void setCsid(Integer csid) {
		this.csid = csid;
	}

	public Integer getClass_() {
		return this.class_;
	}

	public void setClass_(Integer class_) {
		this.class_ = class_;
	}

	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	public String getCsadd() {
		return this.csadd;
	}

	public void setCsadd(String csadd) {
		this.csadd = csadd;
	}

}
