package hibernate;
// Generated 2016-9-8 14:30:58 by Hibernate Tools 3.5.0.Final

/**
 * ES generated by hbm2java
 */
public class ES implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private String ssex;
	private Integer sage;
	private Double sh;
	private Double sw;
	private String sadd;
	private String spwd;

	public ES() {
	}

	public ES(String spwd) {
		this.spwd = spwd;
	}

	public ES(String sname, String ssex, Integer sage, Double sh, Double sw, String sadd, String spwd) {
		this.sname = sname;
		this.ssex = ssex;
		this.sage = sage;
		this.sh = sh;
		this.sw = sw;
		this.sadd = sadd;
		this.spwd = spwd;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSsex() {
		return this.ssex;
	}

	public void setSsex(String ssex) {
		this.ssex = ssex;
	}

	public Integer getSage() {
		return this.sage;
	}

	public void setSage(Integer sage) {
		this.sage = sage;
	}

	public Double getSh() {
		return this.sh;
	}

	public void setSh(Double sh) {
		this.sh = sh;
	}

	public Double getSw() {
		return this.sw;
	}

	public void setSw(Double sw) {
		this.sw = sw;
	}

	public String getSadd() {
		return this.sadd;
	}

	public void setSadd(String sadd) {
		this.sadd = sadd;
	}

	public String getSpwd() {
		return this.spwd;
	}

	public void setSpwd(String spwd) {
		this.spwd = spwd;
	}

}
