package hibernate;
// Generated 2016-9-18 20:33:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * RCheckin generated by hbm2java
 */
public class RCheckin implements java.io.Serializable {

	private Integer rckid;
	private int sid;
	private int cid;
	private Date date;

	public RCheckin() {
	}

	public RCheckin(int sid, int cid, Date date) {
		this.sid = sid;
		this.cid = cid;
		this.date = date;
	}

	public Integer getRckid() {
		return this.rckid;
	}

	public void setRckid(Integer rckid) {
		this.rckid = rckid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
