package hibernate;
// Generated 2016-9-17 23:20:30 by Hibernate Tools 3.5.0.Final

/**
 * RCheckin generated by hbm2java
 */
public class RCheckin implements java.io.Serializable {

	private RCheckinId id;

	public RCheckin() {
	}

	public RCheckin(RCheckinId id) {
		this.id = id;
	}

	public RCheckinId getId() {
		return this.id;
	}

	public void setId(RCheckinId id) {
		this.id = id;
	}

}
