package hibernate;
// Generated 2016-9-13 19:11:22 by Hibernate Tools 3.5.0.Final

/**
 * RSchoolhome generated by hbm2java
 */
public class RSchoolhome implements java.io.Serializable {

	private RSchoolhomeId id;

	public RSchoolhome() {
	}

	public RSchoolhome(RSchoolhomeId id) {
		this.id = id;
	}

	public RSchoolhomeId getId() {
		return this.id;
	}

	public void setId(RSchoolhomeId id) {
		this.id = id;
	}

}
