package hibernate;
// Generated 2016-9-17 23:20:30 by Hibernate Tools 3.5.0.Final

/**
 * RSchoolhomeId generated by hbm2java
 */
public class RSchoolhomeId implements java.io.Serializable {

	private int pid;
	private int tid;

	public RSchoolhomeId() {
	}

	public RSchoolhomeId(int pid, int tid) {
		this.pid = pid;
		this.tid = tid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RSchoolhomeId))
			return false;
		RSchoolhomeId castOther = (RSchoolhomeId) other;

		return (this.getPid() == castOther.getPid()) && (this.getTid() == castOther.getTid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPid();
		result = 37 * result + this.getTid();
		return result;
	}

}
