package hibernate;
// Generated 2016-9-18 20:33:49 by Hibernate Tools 3.5.0.Final

/**
 * RStudentparent generated by hbm2java
 */
public class RStudentparent implements java.io.Serializable {

	private Integer rspid;
	private int pid;
	private int sid;

	public RStudentparent() {
	}

	public RStudentparent(int pid, int sid) {
		this.pid = pid;
		this.sid = sid;
	}

	public Integer getRspid() {
		return this.rspid;
	}

	public void setRspid(Integer rspid) {
		this.rspid = rspid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

}
