package hibernate;
// Generated 2016-9-13 19:11:22 by Hibernate Tools 3.5.0.Final

/**
 * RStudentparentId generated by hbm2java
 */
public class RStudentparentId implements java.io.Serializable {

	private int pid;
	private int sid;

	public RStudentparentId() {
	}

	public RStudentparentId(int pid, int sid) {
		this.pid = pid;
		this.sid = sid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RStudentparentId))
			return false;
		RStudentparentId castOther = (RStudentparentId) other;

		return (this.getPid() == castOther.getPid()) && (this.getSid() == castOther.getSid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPid();
		result = 37 * result + this.getSid();
		return result;
	}

}
