package hibernate;
// Generated 2016-9-17 23:20:30 by Hibernate Tools 3.5.0.Final

/**
 * RStudentparent generated by hbm2java
 */
public class RStudentparent implements java.io.Serializable {

	private RStudentparentId id;

	public RStudentparent() {
	}

	public RStudentparent(RStudentparentId id) {
		this.id = id;
	}

	public RStudentparentId getId() {
		return this.id;
	}

	public void setId(RStudentparentId id) {
		this.id = id;
	}

}
