package hibernate;
// Generated 2016-9-18 20:33:49 by Hibernate Tools 3.5.0.Final

/**
 * RStudentclass generated by hbm2java
 */
public class RStudentclass implements java.io.Serializable {

	private int sid;
	private Integer csid;

	public RStudentclass() {
	}

	public RStudentclass(int sid) {
		this.sid = sid;
	}

	public RStudentclass(int sid, Integer csid) {
		this.sid = sid;
		this.csid = csid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public Integer getCsid() {
		return this.csid;
	}

	public void setCsid(Integer csid) {
		this.csid = csid;
	}

}
