package hibernate;
// Generated 2016-9-18 20:33:49 by Hibernate Tools 3.5.0.Final

/**
 * RTeacherincharge generated by hbm2java
 */
public class RTeacherincharge implements java.io.Serializable {

	private int csid;
	private Integer tid;

	public RTeacherincharge() {
	}

	public RTeacherincharge(int csid) {
		this.csid = csid;
	}

	public RTeacherincharge(int csid, Integer tid) {
		this.csid = csid;
		this.tid = tid;
	}

	public int getCsid() {
		return this.csid;
	}

	public void setCsid(int csid) {
		this.csid = csid;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

}
